language: ruby
rvm:
  - jruby-19mode
  - rbx-19mode
  - 1.9.3
  - 2.0.0
env:
  global:
    - secure: "Ry6INhL05+XfREUEDBbe0hhui/ijy6BZh2Ez8AtCEudUE3pfm5iQla5Su3lYolUozStGFziwMxRsUHsO25gHH/f1NHjcosipYOmE2F61nktLIUMYDOJTG1rRWBa4NUqnDZr1xF/nt7vurJAjtigJ9nVjir1TRg5Cq+DSNkJvNhY="
    - secure: "GBobTOhIPyscc66OPINuhCP7N9sPl4FC+Q1af0EdGEI2AackbrUeHKLbCTJuiHGGaTQWMSfKZGA6esndq5TP1pxQ4T4NtAFpsqHDgyzknhsYxAQ0Zjef8iQAkCaMHJNUbhzFBKCQ8nhhn+9bmNAfXMPYqjrHfx82/IAEU+YehEQ="
    - secure: "c+BxhKEOKaoL1d/qdLHQ4Wca+1m75Xbjm76haOadim85aPFjMlTU2dpFJ8ZJlJQs3awO9LjQR0DBKpTHoNveb5f+7AZx3PSKmQXQyiAQqM+xl4ZOGzl3rkapsP3CGEd5AVSsOQ19m/lJWzWAdN7kXYId2AchW5w8NKM3r8j99Dg="
